name: "CI"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  check:
    name: ${{ matrix.system }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            system: x86_64-linux
          - os: ubuntu-24.04-arm
            system: aarch64-linux
          - os: macos-14
            system: aarch64-darwin
    steps:
      - uses: actions/checkout@v4

      - name: Install Rosetta 2
        if: ${{ matrix.rosetta }}
        run: sudo softwareupdate --install-rosetta --agree-to-license

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/determinate-nix-action@v3
        with:
          extra-conf: ${{ matrix.rosetta && 'extra-platforms = x86_64-darwin' || '' }}

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: caddy-plugins-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Run Nix Checks
        run: nix flake check -L --option system ${{ matrix.system }}
