name: "Auto-update Caddy and Plugins"

on:
  schedule:
    - cron: '0 3 * * *' # Nightly at 3:00 AM
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Update inputs and recalculate hashes
        run: |
          nix flake update
          chmod +x update_hashes.sh
          ./update_hashes.sh

      - name: Create Pull Request with updates
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "chore: update caddy and plugins"
          title: "🚀 Update Caddy & Plugins"
          body: "Automated rebuild with latest Nixpkgs and Caddy plugins."
          branch: "update-caddy"
          delete-branch: true
