name: "Auto-update Caddy and Plugins"

on:
  schedule:
    - cron: '0 3 * * *' # Nightly at 3:00 AM
  workflow_dispatch:

jobs:
  upgrade:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Install Magic Nix Cache
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: caddy-plugins-flake
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: false

      - name: Update inputs and recalculate hashes
        run: |
          nix flake update
          uv run update_hashes.py

      - name: Create Pull Request with updates
        id: cpr
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.UPDATE_PR_PAT }}
          commit-message: "chore: update caddy and plugins"
          title: "🚀 Update Caddy & Plugins"
          body: "Automated rebuild with latest Nixpkgs and Caddy plugins."
          branch: "update-caddy"
          delete-branch: true

      - name: Enable Pull Request Automerge
        if: steps.cpr.outputs.pull-request-number != ''
        run: gh pr merge --auto --merge "${{ steps.cpr.outputs.pull-request-number }}"
        env:
          GH_TOKEN: ${{ secrets.UPDATE_PR_PAT }}
